name: build

on: push

jobs:
  build-Android:
    runs-on: macos-latest    
    steps:
    - name: Checkout 
      uses: actions/checkout@v1

    - name: Setup Android signin
      run: |
        echo "${{ secrets.KEYSTORE }}" > jesulayo.keystore.asc
        gpg -d --passphrase "${{ secrets.GPG_PASSWORD }}" --batch jesulayo.keystore.asc > ./Fix/Fix.Android/jesulayo.keystore
    
    - name: Set Android Version
      uses: jesulayo/update-android-version-manifest-action@v1.0.0
      with:
        android-manifest-path: './Fix/Fix.Android/Properties/AndroidManifest.xml'
        version-name: ${{ secrets.APP_VERSION }}
        version-code: ${{ github.run_number }}
        print-file: true

    - name: Restore NuGet packages
      run: nuget restore
      
    - name: Build Android
      run: MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidPackageFormat=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=jesulayo /p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }} /p:AndroidSigningKeyStore=jesulayo.keystore /p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} ./Fix/Fix.Android/Fix.Android.csproj

    - name: Obtain Android APK file
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Fix
        path: Fix/Fix.Android/bin/Release/com.companyname.fix-Signed.apk
